'use client';
import { useState } from 'react';
import { post } from '@/lib/api';
import { useAuthed, useLiveTopic, usePoll } from '@/lib/hooks';
import { fmtUsd, timeAgo } from '@/lib/format';
import { ActionBadge, ConfidenceBar, ErrorBox, SectionTitle, Spinner } from '@/components/ui';

interface Signal {
  id: string; symbol: string; timeframe: string; action: string;
  price_at_signal: number; probability: number; confidence: number;
  risk_reward: number; stop_loss: number | null; take_profit: number | null;
  trailing_stop_pct: number | null; sentiment_score: number | null;
  rationale: string; ai_provider: string; evaluated: boolean;
  was_correct: boolean | null; outcome_return_pct: number | null; created_at: string;
}

interface Strategy {
  id: string; name: string; description: string; timeframe: string;
  is_active: boolean; is_validated: boolean; total_signals: number;
  win_rate: number; profit_factor: number; sharpe_ratio: number; rank_score: number;
}

export default function SignalsPage() {
  const authed = useAuthed();
  const [symbol, setSymbol] = useState('BTCUSDT');
  const [analyzing, setAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<Record<string, unknown> | null>(null);
  const [analysisErr, setAnalysisErr] = useState('');
  const { data: signals, error, loading, reload } = usePoll<Signal[]>('/signals?limit=40', 60_000);
  const { data: strategies } = usePoll<Strategy[]>('/strategies', 300_000);

  useLiveTopic(['signals'], () => reload());

  const analyze = async () => {
    setAnalyzing(true);
    setAnalysisErr('');
    try {
      setAnalysis(await post(`/signals/analyze/${symbol}?timeframe=1h`, undefined, true));
      reload();
    } catch (e) {
      setAnalysisErr(e instanceof Error ? e.message : 'Analysis failed');
    } finally {
      setAnalyzing(false);
    }
  };

  return (
    <div className="space-y-8">
      <SectionTitle
        title="AI trading signals"
        sub="Generated by the quant ensemble + optional LLM review, evaluated hourly against outcomes"
      />

      <section className="glass flex flex-wrap items-end gap-3 p-4">
        <div className="grow">
          <label className="text-xs font-semibold uppercase text-slate-500">Analyze any pair on demand</label>
          <input className="input mt-1 max-w-60 font-mono uppercase" value={symbol}
            onChange={(e) => setSymbol(e.target.value.toUpperCase())} placeholder="BTCUSDT" />
        </div>
        <button className="btn-primary" onClick={analyze} disabled={analyzing || !authed}>
          {analyzing ? 'Running AI agent…' : '🤖 Run analysis'}
        </button>
        {!authed && <span className="text-xs text-slate-400">Sign in to run on-demand analysis</span>}
      </section>
      {analysisErr && <ErrorBox message={analysisErr} />}
      {analysis && (
        <section className="glass animate-slide-up border-accent/40 p-5">
          <div className="flex flex-wrap items-center gap-3">
            <ActionBadge action={String(analysis.action)} />
            <span className="text-lg font-bold">{String(analysis.symbol)}</span>
            <span className="font-mono">{fmtUsd(Number(analysis.price))}</span>
            <span className="text-sm text-slate-400">prob {(Number(analysis.probability) * 100).toFixed(0)}%</span>
            <ConfidenceBar value={Number(analysis.confidence)} />
            <span className="text-sm text-slate-400">R:R {String(analysis.risk_reward)}</span>
          </div>
          <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{String(analysis.rationale)}</p>
          <div className="mt-3 flex flex-wrap gap-4 font-mono text-sm">
            <span>SL: <b className="text-bear">{fmtUsd(analysis.stop_loss as number)}</b></span>
            <span>TP: <b className="text-bull">{fmtUsd(analysis.take_profit as number)}</b></span>
            {analysis.trailing_stop_pct != null && <span>Trail: <b>{String(analysis.trailing_stop_pct)}%</b></span>}
          </div>
        </section>
      )}

      {strategies && strategies.length > 0 && (
        <section>
          <SectionTitle title="Strategy leaderboard" sub="Ranked by the continuous evaluation pipeline" />
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            {strategies.map((s) => (
              <div key={s.id} className="glass glass-hover p-4">
                <div className="flex items-center justify-between">
                  <h3 className="font-bold">{s.name}</h3>
                  {s.is_validated && <span className="badge bg-bull/15 text-bull">validated</span>}
                </div>
                <p className="mt-1 line-clamp-2 text-xs text-slate-500">{s.description}</p>
                <div className="mt-3 grid grid-cols-2 gap-2 text-xs">
                  <div>Win rate <b>{s.win_rate.toFixed(1)}%</b></div>
                  <div>PF <b>{s.profit_factor.toFixed(2)}</b></div>
                  <div>Sharpe <b>{s.sharpe_ratio.toFixed(2)}</b></div>
                  <div>Signals <b>{s.total_signals}</b></div>
                </div>
                <div className="mt-2 text-right text-xs text-slate-400">score {s.rank_score.toFixed(1)} · {s.timeframe}</div>
              </div>
            ))}
          </div>
        </section>
      )}

      <section>
        <SectionTitle title="Latest signals" />
        {loading && <Spinner />}
        {error && <ErrorBox message={error} />}
        <div className="space-y-3">
          {(signals ?? []).map((s) => (
            <div key={s.id} className="glass glass-hover p-4">
              <div className="flex flex-wrap items-center gap-3">
                <ActionBadge action={s.action} />
                <span className="font-bold">{s.symbol}</span>
                <span className="badge bg-slate-100 dark:bg-white/10">{s.timeframe}</span>
                <span className="font-mono text-sm">{fmtUsd(s.price_at_signal)}</span>
                <ConfidenceBar value={s.confidence} />
                <span className="ml-auto text-xs text-slate-400">{timeAgo(s.created_at)} · {s.ai_provider}</span>
              </div>
              <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{s.rationale}</p>
              <div className="mt-2 flex flex-wrap gap-4 text-xs font-mono">
                {s.stop_loss != null && <span>SL <b className="text-bear">{fmtUsd(s.stop_loss)}</b></span>}
                {s.take_profit != null && <span>TP <b className="text-bull">{fmtUsd(s.take_profit)}</b></span>}
                <span>R:R <b>{s.risk_reward}</b></span>
                {s.sentiment_score != null && <span>sentiment <b>{s.sentiment_score.toFixed(2)}</b></span>}
                {s.evaluated && (
                  <span className={s.was_correct ? 'text-bull' : 'text-bear'}>
                    outcome {s.outcome_return_pct?.toFixed(2)}% {s.was_correct ? '✓ correct' : '✗ wrong'}
                  </span>
                )}
              </div>
            </div>
          ))}
          {signals?.length === 0 && (
            <p className="py-8 text-center text-sm text-slate-400">
              No signals yet — the signal worker publishes new ones every few minutes.
            </p>
          )}
        </div>
      </section>
    </div>
  );
}
